#pragma once

#include <morpheus/core/conformance/coro.hpp>
#include <morpheus/core/conformance/ranges.hpp>

#include <cassert>
#include <concepts>
#include <cstddef>
#include <exception>
#include <iterator>
#include <memory>
#include <new>
#include <type_traits>
#include <utility>

namespace morpheus::concurrency
{

namespace detail
{

/// Empty base mixed in to the promise of a generator that uses the default allocator. It deliberately provides no
/// `operator new` so the coroutine frame is allocated through the global `::operator new`, exactly as before the
/// allocator support was added.
struct default_allocator_promise_base
{};

/// Base mixed in to the promise of a generator that uses a custom allocator. It provides the allocator-aware
/// `operator new`/`operator delete` overloads that mirror std::generator: when a coroutine function supplies a
/// leading `std::allocator_arg_t` parameter followed by an allocator, the compiler selects the `operator new`
/// overload below to allocate the coroutine frame. Because `operator delete` only receives the frame pointer and
/// size, the allocator is stashed in a small proxy stored in the bytes immediately preceding the frame so the
/// matching `operator delete` can recover it and release the memory with the same allocator.
template <typename Allocator>
struct allocator_aware_promise_base
{
    using rebound_alloc = typename std::allocator_traits<Allocator>::template rebind_alloc<std::byte>;

    /// Number of bytes reserved ahead of the frame for the allocator proxy, rounded up so the frame pointer handed
    /// back to the compiler remains suitably aligned.
    static constexpr std::size_t proxy_storage_size() noexcept
    {
        constexpr std::size_t proxy_size = sizeof(rebound_alloc);
        constexpr std::size_t alignment = alignof(std::max_align_t);
        return (proxy_size + alignment - 1) & ~(alignment - 1);
    }

    template <typename A>
        requires std::convertible_to<A, Allocator>
    static void* operator new(std::size_t frame_size, std::allocator_arg_t, A& alloc)
    {
        using traits = std::allocator_traits<rebound_alloc>;

        std::size_t const total = frame_size + proxy_storage_size();
        rebound_alloc rebound(alloc);
        std::byte* storage = traits::allocate(rebound, total);
        ::new (storage) rebound_alloc(rebound);
        return storage + proxy_storage_size();
    }

    static void operator delete(void* frame, std::size_t frame_size) noexcept
    {
        using traits = std::allocator_traits<rebound_alloc>;

        std::byte* frame_ptr = static_cast<std::byte*>(frame);
        std::byte* storage = frame_ptr - proxy_storage_size();
        auto* proxy = std::launder(reinterpret_cast<rebound_alloc*>(storage));
        rebound_alloc alloc = *proxy;
        proxy->~rebound_alloc();
        traits::deallocate(alloc, storage, frame_size + proxy_storage_size());
    }
};

} // namespace detail

/// \class Generator
///     Minimal generator type based on coroutines which models std::ranges::input_range. Largely inspired as a
///     temporary solution to bridge missing support for this unil the inclusion of std::generator:
///     https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2502r2.pdf
/// \tparam T
///     The type generated by the generator.
/// \tparam Allocator
///     The allocator used to allocate the coroutine frame. Defaults to void, in which case the coroutine frame is
///     allocated with the global operator new. Allocator support mirrors std::generator: a coroutine function can
///     supply a custom allocator by adding a leading std::allocator_arg_t parameter followed by the allocator. The
///     supplied allocator is then used to allocate (and later release) the generator's coroutine frame.
template <typename T, typename Allocator = void>
struct Generator
{

    struct promise_type;
    using handle_type = coro::coroutine_handle<promise_type>;                           ///< Handle to generator coroutines.
    using value_type = T;                                                               ///< Value type from resulting generation.
    using reference = std::conditional_t<std::is_reference_v<T>, T, value_type const&>; ///< Reference type to the value type.
    using pointer = std::add_pointer_t<reference>;                                      ///< Pointer type to the value type.
    using allocator_type = Allocator;                                                   ///< Allocator used for the coroutine frame (void when unspecified).

    explicit Generator(handle_type h)
        : coro(h)
    {}

    /// Destroys the generator.
    ~Generator()
    {
        if (coro)
            coro.destroy();
    }

    Generator(Generator const&) = delete;
    Generator& operator=(Generator const&) = delete;

    Generator(Generator&& rhs) noexcept
        : coro(std::exchange(rhs.coro, {}))
    {}

    Generator& operator=(Generator&& rhs) noexcept
    {
        coro = std::exchange(rhs.coro, {});
        return *this;
    }

    struct promise_type
        : std::conditional_t<std::is_void_v<Allocator>,
              detail::default_allocator_promise_base,
              detail::allocator_aware_promise_base<Allocator>>
    {
        auto initial_suspend() -> coro::suspend_always { return {}; }

        auto final_suspend() noexcept -> coro::suspend_always { return {}; }

        auto get_return_object() -> Generator { return Generator{handle_type::from_promise(*this)}; }

        auto return_void() -> void {}

        template <std::convertible_to<T> From>
        auto yield_value(From&& from) noexcept(std::is_nothrow_constructible_v<T, From&&>) -> coro::suspend_always
        {
            current_value = std::addressof(from);
            return {};
        }

        void unhandled_exception() { exception = std::current_exception(); }

        std::add_pointer_t<std::add_const_t<T>> current_value = nullptr;
        std::exception_ptr exception;
    };

    /// \class iterator
    ///     Iterator type confroming to an input iterator concept for iterating over the generated sequence.
    class iterator
    {
    public:
        using value_type = Generator::value_type; ///< Value type pointed to by the iterator.
        using reference = Generator::reference;   ///< Reference to the underlying value type pointed to by the iterator.
        using pointer = Generator::pointer;       ///< Pointer to the underlying value type pointed to by the iterator.
        using difference_type = std::ptrdiff_t;
        using iterator_category = std::input_iterator_tag;

        iterator() = default;
        iterator(iterator const& rhs) noexcept = default;
        iterator& operator=(iterator const& other) noexcept = default;

        iterator(iterator&& rhs) noexcept
            : handle(std::exchange(rhs.handle, {}))
        {}

        iterator& operator=(iterator&& other) noexcept
        {
            handle = std::exchange(other.handle, {});
            return *this;
        }

        iterator& operator++()
        {
            assert(!handle.done() && "Can't increment generator end iterator");
            handle.resume();
            if (handle.promise().exception)
            {
                std::rethrow_exception(handle.promise().exception);
            }
            return *this;
        }

        void operator++(int) { ++*this; }

        [[nodiscard]] reference& operator*() const noexcept
        {
            assert(!handle.done() && "Can't dereference generator end iterator");
            return *handle.promise().current_value;
        }

        [[nodiscard]] pointer& operator->() const noexcept { return std::addressof(operator*()); }

        [[nodiscard]] bool operator==(std::default_sentinel_t) const noexcept { return handle.done(); }

    private:
        friend Generator;

        explicit iterator(coro::coroutine_handle<promise_type> h) noexcept
            : handle(h)
        {}

        coro::coroutine_handle<promise_type> handle;
    };

    [[nodiscard]] iterator begin() const noexcept
    {
        // Pre: Coroutine is suspended at its initial suspend point
        assert(coro && "Can't call begin on moved-from generator");
#if (__cpp_impl_coroutine >= 201902L)
        coro.resume();
#else
        const_cast<Generator*>(this)->coro.resume(); // std::experimental::resume is not marked const.
#endif
        if (coro.promise().exception)
        {
            std::rethrow_exception(coro.promise().exception);
        }
        return iterator(coro);
    }

    [[nodiscard]] std::default_sentinel_t end() const noexcept { return std::default_sentinel; }

private:
    handle_type coro;
};

} // namespace morpheus::concurrency

template <typename T, typename Allocator>
inline constexpr bool ::morpheus::conf::ranges::enable_view<morpheus::concurrency::Generator<T, Allocator>> = true;

template <typename T, typename Allocator>
inline constexpr bool ::morpheus::conf::ranges::enable_borrowed_range<morpheus::concurrency::Generator<T, Allocator>> = true;
