name: 'Setup Python'
description: 'Sets up Python and installs requirements (including Conan)'

inputs:
  install-python:
    description: 'Whether to run actions/setup-python'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      if: inputs.install-python == 'true'
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.13'

    - name: Install Python requirements
      shell: bash
      run: |
        pip install -r ./requirements.txt
